grails-app/domain/com/cyberoller/xbi/shiro/Role.groovy
package com.cyberoller.xbi.shiro

class Role {
	//角色名称
    String name
	//别名
    String alias
	//描述
    String description
	//创建日期
	Date dateCreated
	//修改日期
	Date lastUpdated

    static hasMany = [ users: User, permissions: String ]
    static belongsTo = User

    static constraints = {
        name(nullable: false, blank: false, unique: true, maxSize : 50)
        alias(nullable:false, blank:false, unique : true, maxSize : 3)
        description(nullable:true, blank:true, maxSize : 200)
    }

	def beforeValidate(){
    	name = name?.trim()?.toUpperCase()
		alias = alias?.trim()?.toUpperCase()
    	description = description?.trim()
    }

	String toString(){
    	return "${alias}-${name}"
    }

	static mapping = {
    	table "shiro_role"
    }
}

grails-app/domain/com/cyberoller/xbi/shiro/User.groovy
package com.cyberoller.xbi.shiro

/*用户表*/
class User {
	//用户名
    String username
	//全称
    String fullname
	//角色名称
    String roleAlias
	//密码
    String passwordHash
	//盐
    String passwordSalt
    //启用？
    Boolean isActive
	//语言
	String language
	//创建人
	User createdBy
	//修改人
	User lastModifiedBy
    //创建日期
	Date dateCreated
	//修改日期
	Date lastUpdated

    static hasMany = [ roles: Role , permissions: String]

    static constraints = {
		username(nullable: false, blank: false, unique: true, maxSize : 20)
        fullname(nullable:false, blank:false, maxSize : 35)
		roleAlias(nullable:false, blank:false, maxSize : 3)
        passwordHash(nullable:true, blank:false, maxSize : 512)
        passwordSalt(nullable: true, blank:false, maxSize : 64)
		language(nullable:false, blank:false, maxSize:10)
        isActive(nullable:false)
		createdBy(nullable:true)
		lastModifiedBy(nullable:true)
	}

	def beforeValidate(){
    	//用户名大写
    	username = username?.trim()?.toUpperCase()
    	//如果启用为NULL，则更新为FALSE
    	if(this.isActive == null){
    		this.isActive = false
    	}
    }

	String toString(){
    	return "${username}"
    }

	static mapping = {
    	table "shiro_user"
    }
}

grails-app/controllers/com/cyberoller/xbi/shiro/AuthController.groovy
package com.cyberoller.xbi.shiro

import org.apache.shiro.SecurityUtils
import org.apache.shiro.authc.AuthenticationException
import org.apache.shiro.authc.UsernamePasswordToken
import org.apache.shiro.web.util.SavedRequest
import org.apache.shiro.web.util.WebUtils

class AuthController {
    def shiroSecurityManager

    def index = { redirect(action: "login", params: params) }

    def login = {
        render view : "/shiro/auth/login", model : [ username: params.username, rememberMe: (params.rememberMe != null), targetUri: params.targetUri ]
    }

    def signIn = {
        def authToken = new UsernamePasswordToken(params.username?.toUpperCase(), params.password as String)

        // Support for "remember me"
        if (params.rememberMe) {
            authToken.rememberMe = true
        }
        
        // If a controller redirected to this page, redirect back
        // to it. Otherwise redirect to the root URI.
        def targetUri = params.targetUri ?: "/"
        
        // Handle requests saved by Shiro filters.
        SavedRequest savedRequest = WebUtils.getSavedRequest(request)
        if (savedRequest) {
            targetUri = savedRequest.requestURI - request.contextPath
            if (savedRequest.queryString) targetUri = targetUri + '?' + savedRequest.queryString
        }
        
        try{
            // Perform the actual login. An AuthenticationException
            // will be thrown if the username is unrecognised or the
            // password is incorrect.
            SecurityUtils.subject.login(authToken)

            log.info "Redirecting to '${targetUri}'."
            redirect(uri: targetUri)
        }
        catch (AuthenticationException ex){
            // Authentication failed, so display the appropriate message
            // on the login page.
            log.info "Authentication failure for user '${params.username}'."
            switch(ex){
            	case AccountInactiveException :
            		flash.message = "login.account.inactive"
            		flash.args = ["${params.username}"]
					flash.default = ex.getMessage()
            		break
            	default :
            		flash.message = "login.failed"
            		flash.args = null
					flash.default = ex.getMessage()
            }

            // Keep the username and "remember me" setting so that the
            // user doesn't have to enter them again.
            def m = [ username: params.username ]
            if (params.rememberMe) {
                m["rememberMe"] = true
            }

            // Remember the target URI too.
            if (params.targetUri) {
                m["targetUri"] = params.targetUri
            }

            // Now redirect back to the login page.
            redirect(action: "login", params: m)
        }
    }

    def signOut = {
        // Log the user out of the application.
        SecurityUtils.subject?.logout()
        webRequest.getCurrentRequest().session = null

        // For now, redirect back to the home page.
        redirect(uri: "/")
    }

    def unauthorized = {
        render "You do not have permission to access this page."
    }
}

grails-app/controllers/com/cyberoller/xbi/shiro/RoleController.groovy
package com.cyberoller.xbi.shiro

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class RoleController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond view:"/shiro/role/index", Role.list(params), model:[roleInstanceCount: Role.count()]
    }

    def show(Role roleInstance) {
        respond view:"/shiro/role/show",roleInstance
    }

    def create() {
        respond view:"/shiro/role/create", new Role(params)
    }

    @Transactional
    def save(Role roleInstance) {
        if (roleInstance == null) {
            notFound()
            return
        }

        if (roleInstance.hasErrors()) {
            respond roleInstance.errors, view:'/shiro/role/create'
            return
        }

        roleInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'roleInstance.label', default: 'Role'), roleInstance.id])
                redirect roleInstance
            }
            '*' { respond roleInstance, [status: CREATED] }
        }
    }

    def edit(Role roleInstance) {
        respond view:"/shiro/role/edit",roleInstance
    }

    @Transactional
    def update(Role roleInstance) {
        if (roleInstance == null) {
            notFound()
            return
        }

        if (roleInstance.hasErrors()) {
            respond roleInstance.errors, view:'/shiro/role/edit'
            return
        }

        roleInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Role.label', default: 'Role'), roleInstance.id])
                redirect roleInstance
            }
            '*'{ respond roleInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Role roleInstance) {

        if (roleInstance == null) {
            notFound()
            return
        }

        roleInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Role.label', default: 'Role'), roleInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'roleInstance.label', default: 'Role'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/controllers/com/cyberoller/xbi/shiro/UserController.groovy
package com.cyberoller.xbi.shiro



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class UserController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond view : "/shiro/user/index", User.list(params), model:[userInstanceCount: User.count()]
    }

    def show(User userInstance) {
        respond view : "/shiro/user/show", userInstance
    }

    def create() {
        respond new User(params)
    }

    @Transactional
    def save(User userInstance) {
        if (userInstance == null) {
            notFound()
            return
        }

        if (userInstance.hasErrors()) {
            respond userInstance.errors, view:'create'
            return
        }

        userInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'userInstance.label', default: 'User'), userInstance.id])
                redirect userInstance
            }
            '*' { respond userInstance, [status: CREATED] }
        }
    }

    def edit(User userInstance) {
        respond view : "/shiro/user/edit", userInstance
    }

    @Transactional
    def update(User userInstance) {
        if (userInstance == null) {
            notFound()
            return
        }

        if (userInstance.hasErrors()) {
            respond userInstance.errors, view:'edit'
            return
        }

        userInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'User.label', default: 'User'), userInstance.id])
                redirect userInstance
            }
            '*'{ respond userInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(User userInstance) {

        if (userInstance == null) {
            notFound()
            return
        }

        userInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'User.label', default: 'User'), userInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'userInstance.label', default: 'User'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/shiro/user/_edit.gsp
<%@ page import="com.cyberoller.xbi.shiro.User" %>

<div class="fieldcontain ${hasErrors(bean: userInstance, field: 'username', 'error')} required">
	<label for="username">
		<g:message code="user.username.label" default="Username" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="username" maxlength="20" required="" value="${userInstance?.username}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: userInstance, field: 'fullname', 'error')} required">
	<label for="fullname">
		<g:message code="user.fullname.label" default="Fullname" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="fullname" maxlength="35" required="" value="${userInstance?.fullname}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: userInstance, field: 'roleAlias', 'error')} required">
	<label for="roleAlias">
		<g:message code="user.roleAlias.label" default="Role Alias" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="roleAlias" maxlength="3" required="" value="${userInstance?.roleAlias}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: userInstance, field: 'language', 'error')} required">
	<label for="language">
		<g:message code="user.language.label" default="Language" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="language" maxlength="10" required="" value="${userInstance?.language}"/>
</div>

grails-app/views/shiro/user/_index.gsp
<%@ page import="com.cyberoller.xbi.shiro.User" %>
<table>
	<thead>
		<tr>
			<g:sortableColumn property="username" title="${message(code: 'user.username.label', default: 'Username')}" />
			<g:sortableColumn property="fullname" title="${message(code: 'user.fullname.label', default: 'Fullname')}" />
			<g:sortableColumn property="roleAlias" title="${message(code: 'user.roleAlias.label', default: 'Role Alias')}" />
			<g:sortableColumn property="language" title="${message(code: 'user.language.label', default: 'Language')}" />
			<g:sortableColumn property="language" title="${message(code: 'user.isActive.label', default: 'Active?')}" />
			<g:sortableColumn property="dateCreated" title="${message(code: 'user.dateCreated.label', default: 'Date Created')}" />
			<g:sortableColumn property="lastUpdated" title="${message(code: 'user.lastUpdated.label', default: 'Last Updated')}" />
		</tr>
	</thead>
	<tbody>
	<g:each in="${userInstanceList}" status="i" var="userInstance">
		<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
			<td><g:link action="show" id="${userInstance.id}">${fieldValue(bean: userInstance, field: "username")}</g:link></td>
			<td>${fieldValue(bean: userInstance, field: "fullname")}</td>
			<td>${fieldValue(bean: userInstance, field: "roleAlias")}</td>
			<td>${fieldValue(bean: userInstance, field: "language")}</td>
			<td><g:formatBoolean boolean="${userInstance?.isActive}" /></td>
			<td><g:formatDate date="${userInstance?.dateCreated}"/></td>
			<td><g:formatDate date="${userInstance?.lastUpdated}"/></td>
		</tr>
	</g:each>
	</tbody>
</table>
<div class="pagination">
	<g:paginate total="${userInstanceCount ?: 0}" />
</div>

grails-app/views/shiro/user/_show.gsp
<%@ page import="com.cyberoller.xbi.shiro.User" %>

<ol class="property-list user">

	<g:if test="${userInstance?.username}">
	<li class="fieldcontain">
		<span id="username-label" class="property-label"><g:message code="user.username.label" default="Username" /></span>
		<span class="property-value" aria-labelledby="username-label"><g:fieldValue bean="${userInstance}" field="username"/></span>
	</li>
	</g:if>

	<g:if test="${userInstance?.fullname}">
	<li class="fieldcontain">
		<span id="fullname-label" class="property-label"><g:message code="user.fullname.label" default="Fullname" /></span>
		<span class="property-value" aria-labelledby="fullname-label"><g:fieldValue bean="${userInstance}" field="fullname"/></span>
	</li>
	</g:if>

	<g:if test="${userInstance?.roleAlias}">
	<li class="fieldcontain">
		<span id="roleAlias-label" class="property-label"><g:message code="user.roleAlias.label" default="Role Alias" /></span>
		<span class="property-value" aria-labelledby="roleAlias-label"><g:fieldValue bean="${userInstance}" field="roleAlias"/></span>
	</li>
	</g:if>

	<g:if test="${userInstance?.language}">
	<li class="fieldcontain">
		<span id="language-label" class="property-label"><g:message code="user.language.label" default="Language" /></span>
		<span class="property-value" aria-labelledby="language-label"><g:fieldValue bean="${userInstance}" field="language"/></span>
	</li>
	</g:if>

	<g:if test="${userInstance?.isActive}">
	<li class="fieldcontain">
		<span id="isActive-label" class="property-label"><g:message code="user.isActive.label" default="Is Active" /></span>
		<span class="property-value" aria-labelledby="isActive-label"><g:formatBoolean boolean="${userInstance?.isActive}" /></span>
	</li>
	</g:if>

	<g:if test="${userInstance?.createdBy}">
	<li class="fieldcontain">
		<span id="createdBy-label" class="property-label"><g:message code="user.createdBy.label" default="Created By" /></span>
			<span class="property-value" aria-labelledby="createdBy-label"><g:link controller="user" action="show" id="${userInstance?.createdBy?.id}">${userInstance?.createdBy?.encodeAsHTML()}</g:link></span>
		
	</li>
	</g:if>

	<g:if test="${userInstance?.lastModifiedBy}">
	<li class="fieldcontain">
		<span id="lastModifiedBy-label" class="property-label"><g:message code="user.lastModifiedBy.label" default="Last Modified By" /></span>
		<span class="property-value" aria-labelledby="lastModifiedBy-label">
			<g:link controller="user" action="show" id="${userInstance?.lastModifiedBy?.id}">
				${userInstance?.lastModifiedBy?.encodeAsHTML()}
			</g:link>
		</span>
	</li>
	</g:if>

	<g:if test="${userInstance?.roles}">
	<li class="fieldcontain">
		<span id="roles-label" class="property-label"><g:message code="user.roles.label" default="Roles" /></span>
		<g:each in="${userInstance.roles}" var="r">
			<span class="property-value" aria-labelledby="roles-label"><g:link controller="role" action="show" id="${r.id}">${r?.encodeAsHTML()}</g:link></span>
		</g:each>
	</li>
	</g:if>

	<g:if test="${userInstance?.permissions}">
	<li class="fieldcontain">
		<span id="permissions-label" class="property-label"><g:message code="user.permissions.label" default="Permissions" /></span>
		<span class="property-value" aria-labelledby="permissions-label"><g:fieldValue bean="${userInstance}" field="permissions"/></span>
	</li>
	</g:if>


	<g:if test="${userInstance?.dateCreated}">
	<li class="fieldcontain">
		<span id="dateCreated-label" class="property-label"><g:message code="user.dateCreated.label" default="Date Created" /></span>
		<span class="property-value" aria-labelledby="dateCreated-label"><g:formatDate date="${userInstance?.dateCreated}" /></span>
	</li>
	</g:if>

	<g:if test="${userInstance?.lastUpdated}">
	<li class="fieldcontain">
		<span id="lastUpdated-label" class="property-label"><g:message code="user.lastUpdated.label" default="Last Updated" /></span>
		<span class="property-value" aria-labelledby="lastUpdated-label"><g:formatDate date="${userInstance?.lastUpdated}" /></span>
	</li>
	</g:if>

</ol>

grails-app/views/shiro/user/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'user.label', default: 'User')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-user" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-user" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${userInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${userInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:userInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/shiro/user/edit.gsp
<%@ page import="com.cyberoller.xbi.shiro.User" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'user.label', default: 'User')}" />
		<title>
			<g:message code="default.edit.label" args="[entityName]" />
			~
			<g:message code="global.app.name" default="XBI -  AS" />
		</title>
	</head>
	<body>
		<a href="#edit-user" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>

		<div id="edit-user" class="content scaffold-edit" role="main">

			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>

			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>

			<g:hasErrors bean="${userInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${userInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>

			<g:form url="[resource:userInstance, action:'update']" method="PUT" >

				<g:hiddenField name="version" value="${userInstance?.version}" />

				<fieldset class="form">
					<g:render template="/shiro/user/edit" />
				</fieldset>

				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/shiro/user/index.gsp
<%@ page import="com.cyberoller.xbi.shiro.User" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">

		<g:set var="entityName" value="${message(code: 'user.label', default: 'User')}" />
		
		<title>
		
			<g:message code="default.list.label" args="[entityName]" />
			~
			<g:message code="global.app.name" default="XBI - AS" />
			
		</title>
	</head>
	<body>
		<a href="#list-user" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>

		<div id="list-user" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			

			<g:render template="/shiro/user/index" />
		
		</div>
	</body>
</html>

grails-app/views/shiro/user/show.gsp
<%@ page import="com.cyberoller.xbi.shiro.User" %>
<!DOCTYPE html>
<html>
	<head>

		<meta name="layout" content="main">

		<g:set var="entityName" value="${message(code: 'user.label', default: 'User')}" />

		<title>
			<g:message code="default.show.label" args="[entityName]" />
			~
			<g:message code="global.app.name" default="XBI - AS" />
		</title>
	</head>
	<body>
		<a href="#show-user" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>

		<div id="show-user" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			
			<g:render template="/shiro/user/show" />

			<g:form url="[resource:userInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${userInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>