grails-app/domain/com/cyberoller/xbi/shiro/Role.groovy
package com.cyberoller.xbi.shiro

class Role {
	//角色名称
    String name
	//别名
    String alias
	//描述
    String description
	//创建日期
	Date dateCreated
	//修改日期
	Date lastUpdated

    static hasMany = [ users: User, permissions: String ]
    static belongsTo = User

    static constraints = {
        name(nullable: false, blank: false, unique: true, maxSize : 50)
        alias(nullable:false, blank:false, unique : true, maxSize : 3)
        description(nullable:true, blank:true, maxSize : 200)
    }

	def beforeValidate(){
    	name = name?.trim()?.toUpperCase()
		alias = alias?.trim()?.toUpperCase()
    	description = description?.trim()
    }

	String toString(){
    	return "${alias}-${name}"
    }

	static mapping = {
    	table "shiro_role"
    }
}

grails-app/domain/com/cyberoller/xbi/shiro/User.groovy
package com.cyberoller.xbi.shiro

/*用户表*/
class User {
	//用户名
    String username
	//全称
    String fullname
	//角色名称
    String roleAlias
	//密码
    String passwordHash
	//盐
    String passwordSalt
    //启用？
    Boolean isActive
	//语言
	String language
	//创建人
	User createdBy
	//修改人
	User lastModifiedBy
    //创建日期
	Date dateCreated
	//修改日期
	Date lastUpdated

    static hasMany = [ roles: Role , permissions: String]

    static constraints = {
		username(nullable: false, blank: false, unique: true, maxSize : 20)
        fullname(nullable:false, blank:false, maxSize : 35)
		roleAlias(nullable:false, blank:false, maxSize : 3)
        passwordHash(nullable:true, blank:false, maxSize : 512)
        passwordSalt(nullable: true, blank:false, maxSize : 64)
		language(nullable:false, blank:false, maxSize:10)
        isActive(nullable:false)
		createdBy(nullable:true)
		lastModifiedBy(nullable:true)
	}

	def beforeValidate(){
    	//用户名大写
    	username = username?.trim()?.toUpperCase()
    	//如果启用为NULL，则更新为FALSE
    	if(this.isActive == null){
    		this.isActive = false
    	}
    }

	String toString(){
    	return "${username}"
    }

	static mapping = {
    	table "shiro_user"
    }
}

grails-app/controllers/com/cyberoller/xbi/shiro/AuthController.groovy
package com.cyberoller.xbi.shiro

import org.apache.shiro.SecurityUtils
import org.apache.shiro.authc.AuthenticationException
import org.apache.shiro.authc.UsernamePasswordToken
import org.apache.shiro.web.util.SavedRequest
import org.apache.shiro.web.util.WebUtils

class AuthController {
    def shiroSecurityManager

    def index = { redirect(action: "login", params: params) }

    def login = {
        render view : "/shiro/auth/login", model : [ username: params.username, rememberMe: (params.rememberMe != null), targetUri: params.targetUri ]
    }

    def signIn = {
        def authToken = new UsernamePasswordToken(params.username?.toUpperCase(), params.password as String)

        // Support for "remember me"
        if (params.rememberMe) {
            authToken.rememberMe = true
        }
        
        // If a controller redirected to this page, redirect back
        // to it. Otherwise redirect to the root URI.
        def targetUri = params.targetUri ?: "/"
        
        // Handle requests saved by Shiro filters.
        SavedRequest savedRequest = WebUtils.getSavedRequest(request)
        if (savedRequest) {
            targetUri = savedRequest.requestURI - request.contextPath
            if (savedRequest.queryString) targetUri = targetUri + '?' + savedRequest.queryString
        }
        
        try{
            // Perform the actual login. An AuthenticationException
            // will be thrown if the username is unrecognised or the
            // password is incorrect.
            SecurityUtils.subject.login(authToken)

            log.info "Redirecting to '${targetUri}'."
            redirect(uri: targetUri)
        }
        catch (AuthenticationException ex){
            // Authentication failed, so display the appropriate message
            // on the login page.
            log.info "Authentication failure for user '${params.username}'."
            switch(ex){
            	case AccountInactiveException :
            		flash.message = "login.account.inactive"
            		flash.args = ["${params.username}"]
					flash.default = ex.getMessage()
            		break
            	default :
            		flash.message = "login.failed"
            		flash.args = null
					flash.default = ex.getMessage()
            }

            // Keep the username and "remember me" setting so that the
            // user doesn't have to enter them again.
            def m = [ username: params.username ]
            if (params.rememberMe) {
                m["rememberMe"] = true
            }

            // Remember the target URI too.
            if (params.targetUri) {
                m["targetUri"] = params.targetUri
            }

            // Now redirect back to the login page.
            redirect(action: "login", params: m)
        }
    }

    def signOut = {
        // Log the user out of the application.
        SecurityUtils.subject?.logout()
        webRequest.getCurrentRequest().session = null

        // For now, redirect back to the home page.
        redirect(uri: "/")
    }

    def unauthorized = {
        render "You do not have permission to access this page."
    }
}

grails-app/controllers/com/cyberoller/xbi/shiro/RoleController.groovy
package com.cyberoller.xbi.shiro

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class RoleController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond view:"/shiro/role/index", Role.list(params), model:[roleInstanceCount: Role.count()]
    }

    def show(Role roleInstance) {
        respond view:"/shiro/role/show",roleInstance
    }

    def create() {
        respond view:"/shiro/role/create", new Role(params)
    }

    @Transactional
    def save(Role roleInstance) {
        if (roleInstance == null) {
            notFound()
            return
        }

        if (roleInstance.hasErrors()) {
            respond roleInstance.errors, view:'/shiro/role/create'
            return
        }

        roleInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'roleInstance.label', default: 'Role'), roleInstance.id])
                redirect roleInstance
            }
            '*' { respond roleInstance, [status: CREATED] }
        }
    }

    def edit(Role roleInstance) {
        respond view:"/shiro/role/edit",roleInstance
    }

    @Transactional
    def update(Role roleInstance) {
        if (roleInstance == null) {
            notFound()
            return
        }

        if (roleInstance.hasErrors()) {
            respond roleInstance.errors, view:'/shiro/role/edit'
            return
        }

        roleInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Role.label', default: 'Role'), roleInstance.id])
                redirect roleInstance
            }
            '*'{ respond roleInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Role roleInstance) {

        if (roleInstance == null) {
            notFound()
            return
        }

        roleInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Role.label', default: 'Role'), roleInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'roleInstance.label', default: 'Role'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/controllers/com/cyberoller/xbi/shiro/UserController.groovy
package com.cyberoller.xbi.shiro



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class UserController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond view : "/shiro/user/index", User.list(params), model:[userInstanceCount: User.count()]
    }

    def show(User userInstance) {
        respond view : "/shiro/user/show", userInstance
    }

    def create() {
        respond new User(params)
    }

    @Transactional
    def save(User userInstance) {
        if (userInstance == null) {
            notFound()
            return
        }

        if (userInstance.hasErrors()) {
            respond userInstance.errors, view:'create'
            return
        }

        userInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'userInstance.label', default: 'User'), userInstance.id])
                redirect userInstance
            }
            '*' { respond userInstance, [status: CREATED] }
        }
    }

    def edit(User userInstance) {
        respond view : "/shiro/user/edit", userInstance
    }

    @Transactional
    def update(User userInstance) {
        if (userInstance == null) {
            notFound()
            return
        }

        if (userInstance.hasErrors()) {
            respond userInstance.errors, view:'edit'
            return
        }

        userInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'User.label', default: 'User'), userInstance.id])
                redirect userInstance
            }
            '*'{ respond userInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(User userInstance) {

        if (userInstance == null) {
            notFound()
            return
        }

        userInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'User.label', default: 'User'), userInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'userInstance.label', default: 'User'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/shiro/role/_edit.gsp
<%@ page import="com.cyberoller.xbi.shiro.Role" %>



<div class="fieldcontain ${hasErrors(bean: roleInstance, field: 'name', 'error')} required">
	<label for="name">
		<g:message code="role.name.label" default="Name" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="name" maxlength="50" required="" value="${roleInstance?.name}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: roleInstance, field: 'alias', 'error')} required">
	<label for="alias">
		<g:message code="role.alias.label" default="Alias" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="alias" maxlength="3" required="" value="${roleInstance?.alias}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: roleInstance, field: 'description', 'error')} ">
	<label for="description">
		<g:message code="role.description.label" default="Description" />
		
	</label>
	<g:textField name="description" maxlength="200" value="${roleInstance?.description}"/>

</div>

grails-app/views/shiro/role/_index.gsp
<%@ page import="com.cyberoller.xbi.shiro.Role" %>

<table>
<thead>
		<tr>
			<g:sortableColumn property="name" title="${message(code: 'role.name.label', default: 'Name')}" />
			<g:sortableColumn property="alias" title="${message(code: 'role.alias.label', default: 'Alias')}" />
			<g:sortableColumn property="description" title="${message(code: 'role.description.label', default: 'Description')}" />
			<g:sortableColumn property="dateCreated" title="${message(code: 'role.dateCreated.label', default: 'Date Created')}" />
			<g:sortableColumn property="lastUpdated" title="${message(code: 'role.lastUpdated.label', default: 'Last Updated')}" />
		</tr>
	</thead>
	<tbody>
	<g:each in="${roleInstanceList}" status="i" var="roleInstance">
		<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
			<td><g:link action="show" id="${roleInstance.id}">${fieldValue(bean: roleInstance, field: "name")}</g:link></td>
			<td>${fieldValue(bean: roleInstance, field: "alias")}</td>
			<td>${fieldValue(bean: roleInstance, field: "description")}</td>
			<td><g:formatDate date="${roleInstance.dateCreated}" /></td>
			<td><g:formatDate date="${roleInstance.lastUpdated}" /></td>
		</tr>
	</g:each>
	</tbody>
</table>
<div class="pagination">
	<g:paginate total="${roleInstanceCount ?: 0}" />
</div>

grails-app/views/shiro/role/_show.gsp
<%@ page import="com.cyberoller.xbi.shiro.Role" %>
<ol class="property-list role">

	<g:if test="${roleInstance?.name}">
	<li class="fieldcontain">
		<span id="name-label" class="property-label"><g:message code="role.name.label" default="Name" /></span>
		<span class="property-value" aria-labelledby="name-label"><g:fieldValue bean="${roleInstance}" field="name"/></span>
	</li>
	</g:if>

	<g:if test="${roleInstance?.alias}">
	<li class="fieldcontain">
		<span id="alias-label" class="property-label"><g:message code="role.alias.label" default="Alias" /></span>
		<span class="property-value" aria-labelledby="alias-label"><g:fieldValue bean="${roleInstance}" field="alias"/></span>
	</li>
	</g:if>

	<g:if test="${roleInstance?.description}">
	<li class="fieldcontain">
		<span id="description-label" class="property-label"><g:message code="role.description.label" default="Description" /></span>
		<span class="property-value" aria-labelledby="description-label"><g:fieldValue bean="${roleInstance}" field="description"/></span>
	</li>
	</g:if>


	<g:if test="${roleInstance?.permissions}">
	<li class="fieldcontain">
		<span id="permissions-label" class="property-label"><g:message code="role.permissions.label" default="Permissions" /></span>
		<span class="property-value" aria-labelledby="permissions-label"><g:fieldValue bean="${roleInstance}" field="permissions"/></span>
	</li>
	</g:if>

	<g:if test="${roleInstance?.users}">
	<li class="fieldcontain">
		<span id="users-label" class="property-label"><g:message code="role.users.label" default="Users" /></span>
		<g:each in="${roleInstance.users}" var="u">
			<span class="property-value" aria-labelledby="users-label"><g:link controller="user" action="show" id="${u.id}">${u?.encodeAsHTML()}</g:link></span>
		</g:each>
	</li>
	</g:if>

	<g:if test="${roleInstance?.dateCreated}">
	<li class="fieldcontain">
		<span id="dateCreated-label" class="property-label"><g:message code="role.dateCreated.label" default="Date Created" /></span>
		<span class="property-value" aria-labelledby="dateCreated-label"><g:formatDate date="${roleInstance?.dateCreated}" /></span>
	</li>
	</g:if>

	<g:if test="${roleInstance?.lastUpdated}">
	<li class="fieldcontain">
		<span id="lastUpdated-label" class="property-label"><g:message code="role.lastUpdated.label" default="Last Updated" /></span>
		<span class="property-value" aria-labelledby="lastUpdated-label"><g:formatDate date="${roleInstance?.lastUpdated}" /></span>
	</li>
	</g:if>


</ol>

grails-app/views/shiro/role/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'role.label', default: 'Role')}" />
		<title>
			<g:message code="default.create.label" args="[entityName]" />
			~
			<g:message code="global.app.name" default="XBI - AS" />
		</title>
	</head>
	<body>

		<a href="#create-role" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		
		<div id="create-role" class="content scaffold-create" role="main">

			<h1><g:message code="default.create.label" args="[entityName]" /></h1>

			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>

			<g:hasErrors bean="${roleInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${roleInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>

			<g:form url="[resource:roleInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="/shiro/role/edit" />
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/shiro/role/edit.gsp
<%@ page import="com.cyberoller.xbi.shiro.Role" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'role.label', default: 'Role')}" />
		<title>
			<g:message code="default.edit.label" args="[entityName]" />
			~
			<g:message code="global.app.name" default="XBI-AS" />
		</title>
	</head>
	<body>
		<a href="#edit-role" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>

		<div id="edit-role" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
		
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			
			<g:hasErrors bean="${roleInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${roleInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			
			<g:form url="[resource:roleInstance, action:'update']" method="PUT" >
			
				<g:hiddenField name="version" value="${roleInstance?.version}" />
				
				<fieldset class="form">
					<g:render template="/shiro/role/edit" />
				</fieldset>

				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/shiro/role/index.gsp
<%@ page import="com.cyberoller.xbi.shiro.Role" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'role.label', default: 'Role')}" />
		<title>
			<g:message code="default.list.label" args="[entityName]" />
			~
			<g:message code="global.app.name" default="XBI_AS" />
		</title>
	</head>
	<body>
		<a href="#list-role" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>

		<div id="list-role" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			
			<g:render template="/shiro/role/index" />
		</div>
	</body>
</html>

grails-app/views/shiro/role/show.gsp
<%@ page import="com.cyberoller.xbi.shiro.Role" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'role.label', default: 'Role')}" />
		<title>
			<g:message code="default.show.label" args="[entityName]" />
			~
			<g:message code="global.app.name" default="XBI-AS" />
		</title>
	</head>
	<body>
		<a href="#show-role" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>

		<div id="show-role" class="content scaffold-show" role="main">

			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>

			
			<g:render template="/shiro/role/show" />

			<g:form url="[resource:roleInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${roleInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>