grails-app/domain/com/cyberoller/xbi/chartjs/Dashboard.groovy
package com.cyberoller.xbi.chartjs

import com.cyberoller.xbi.shiro.User

class Dashboard {
	
	//名称
	String name
	//作者
	String author
	//标题
	String title
	//数据源
	DataSource datasource
	//描述
	String description
	//放在菜单上
	Boolean atMenu
	//菜单顺序
	String menuOrder
	//放在主页
	Boolean homePage
	//启用
	Boolean isActive
	//所有人
	User owner
	//创建人
	User createdBy
	//修改人
	User lastModifiedBy
	//创建日期
	Date dateCreated
	//修改日期
	Date lastUpdated

    static constraints = {
		name(nullable:false, blank:false, unique : true, maxSize: 20)
		author(nullable:true, blank:true, maxSize : 20)
		title(nullable:true, blank:true, maxSize : 200)
		datasource(nullable:false)
		description(nullable:true, blank:true, maxSize : 200)
		atMenu(nullable:false)
		menuOrder(nullalbe:true, maxSize : 2)
		homePage(nullable:false)
		isActive(nullable:false)
    	owner(nullable:false)
    	createdBy(nullable:false)
    	lastModifiedBy(nullable:false)
    }
    
	def beforeValidate(){
    	//名称换成小写
    	name = name?.trim()?.toLowerCase()
    	//如果启用为NULL，则更新为FALSE
    	if(this.isActive == null){
    		this.isActive = false
    	}
		if(this.homePage == null){
    		this.homePage = false
    	}
		if(this.atMenu == null){
    		this.atMenu = false
    	}
    }


    String toString(){
    	return "${name}"
    }
    
    static mapping = {
        table "chartjs_dashboard"
    }
}

grails-app/domain/com/cyberoller/xbi/chartjs/DataSource.groovy
package com.cyberoller.xbi.chartjs

import com.cyberoller.xbi.shiro.User

//数据库连接
class DataSource {

	//名称
	String name
	//地址
	String url
	//用户名
	String username
	//密码
	String password
	//驱动
	String driver
	//描述
	String description
	//所有人
	User owner
	//创建人
	User createdBy
	//修改人
	User lastModifiedBy
	//创建日期
	Date dateCreated
	//修改日期
	Date lastUpdated


    static constraints = {
    	name(nullable:false, blank:false, maxSize : 20)
    	url(nullable:false, blank:false, unique:true, maxSize : 200)
    	username(nullable:false, blank:false, maxSize : 20)
    	password(nullable:false, blank:false, maxSize : 20)
    	driver(nullable:false, blank:false, maxSize : 100)
    	description(nullable:true, blank:true, maxSize : 200)
    	owner(nullable:false)
    	createdBy(nullable:false)
    	lastModifiedBy(nullable:false)
    }
    
	def beforeValidate(){
    	//名称换成小写
    	name = name?.trim()?.toLowerCase()
    	password = password?:""
    }

    
    String toString(){
    	return "${name}"
    }
    
    static mapping = {
        table "chartjs_datasource"
    }

}

grails-app/controllers/com/cyberoller/xbi/chartjs/As001Controller.groovy
package com.cyberoller.xbi.chartjs

class As001Controller {

	//def as001Service

	/*nav*/
    def index(){
		render view : "/chartjs/dashboard/as001/index"
	}

	def products ()  {
	    render view : "/chartjs/dashboard/as001/products"
	}

    def sectors() { 
		render view : "/chartjs/dashboard/as001/sectors"
	}

    def regions() { 
		render view : "/chartjs/dashboard/as001/regions"
	}

    def channels() { 
		render view : "/chartjs/dashboard/as001/channels"
	}
	/*load page*/
	def page ()  {
	    render template : "/chartjs/dashboard/as001/${params.id}"
	}
	/*load data*/
	def sales (){
			if (params?.startDate && params.endDate) {
			render(contentType:"text/json") {
				array{
					"0"(SaleDate:"2014-01-01T00:00:00",Sales:1077700.0)
					"1"(SaleDate:"2014-01-02T00:00:00",Sales:1105350.0)
					"2"(SaleDate:"2014-01-03T00:00:00",Sales:1067100.0)
					"3"(SaleDate:"2014-01-04T00:00:00",Sales:1070100.0)
					"4"(SaleDate:"2014-01-05T00:00:00",Sales:1075600.0)
					"5"(SaleDate:"2014-01-06T00:00:00",Sales:1033600.0)
					"6"(SaleDate:"2014-01-07T00:00:00",Sales:1112550.0)
					"7"(SaleDate:"2014-01-08T00:00:00",Sales:1059350.0)
					"8"(SaleDate:"2014-01-09T00:00:00",Sales:1111700.0)
					"9"(SaleDate:"2014-01-10T00:00:00",Sales:1298350.0)
					"10"(SaleDate:"2014-01-11T00:00:00",Sales:1181300.0)
					"11"(SaleDate:"2014-01-12T00:00:00",Sales:1296800.0)
					"12"(SaleDate:"2014-01-13T00:00:00",Sales:1292550.0)
					"13"(SaleDate:"2014-01-14T00:00:00",Sales:1252300.0)
					"14"(SaleDate:"2014-01-15T00:00:00",Sales:1307250.0)
					"15"(SaleDate:"2014-01-16T00:00:00",Sales:1401900.0)
					"16"(SaleDate:"2014-01-17T00:00:00",Sales:1286100.0)
					"17"(SaleDate:"2014-01-18T00:00:00",Sales:1369550.0)
					"18"(SaleDate:"2014-01-19T00:00:00",Sales:1335200.0)
					"19"(SaleDate:"2014-01-20T00:00:00",Sales:1222800.0)
					"20"(SaleDate:"2014-01-21T00:00:00",Sales:1268100.0)
					"21"(SaleDate:"2014-01-22T00:00:00",Sales:1370000.0)
					"22"(SaleDate:"2014-01-23T00:00:00",Sales:1256300.0)
					"23"(SaleDate:"2014-01-24T00:00:00",Sales:1270250.0)
					"24"(SaleDate:"2014-01-25T00:00:00",Sales:1120400.0)
					"25"(SaleDate:"2014-01-26T00:00:00",Sales:1225650.0)
					"26"(SaleDate:"2014-01-27T00:00:00",Sales:1183300.0)
					"27"(SaleDate:"2014-01-28T00:00:00",Sales:1211850.0)
					"28"(SaleDate:"2014-01-29T00:00:00",Sales:1316450.0)
					"29"(SaleDate:"2014-01-30T00:00:00",Sales:1188900.0)
					"30"(SaleDate:"2014-01-31T00:00:00",Sales:1239550.0)
					"31"(SaleDate:"2014-02-01T00:00:00",Sales:1191150.0)
					"32"(SaleDate:"2014-02-02T00:00:00",Sales:1085700.0)
					"33"(SaleDate:"2014-02-03T00:00:00",Sales:1128000.0)
					"34"(SaleDate:"2014-02-04T00:00:00",Sales:1025250.0)
					"35"(SaleDate:"2014-02-05T00:00:00",Sales:978600.0)
					"36"(SaleDate:"2014-02-06T00:00:00",Sales:1063150.0)
					"37"(SaleDate:"2014-02-07T00:00:00",Sales:1119650.0)
					"38"(SaleDate:"2014-02-08T00:00:00",Sales:1026050.0)
					"39"(SaleDate:"2014-02-09T00:00:00",Sales:1036900.0)
					"40"(SaleDate:"2014-02-10T00:00:00",Sales:1193800.0)
					"41"(SaleDate:"2014-02-11T00:00:00",Sales:1215350.0)
					"42"(SaleDate:"2014-02-12T00:00:00",Sales:1308850.0)
					"43"(SaleDate:"2014-02-13T00:00:00",Sales:1227500.0)
					"44"(SaleDate:"2014-02-14T00:00:00",Sales:1193400.0)
					"45"(SaleDate:"2014-02-15T00:00:00",Sales:1333950.0)
					"46"(SaleDate:"2014-02-16T00:00:00",Sales:1271950.0)
					"47"(SaleDate:"2014-02-17T00:00:00",Sales:1153550.0)
					"48"(SaleDate:"2014-02-18T00:00:00",Sales:1276900.0)
					"49"(SaleDate:"2014-02-19T00:00:00",Sales:1276400.0)
					"50"(SaleDate:"2014-02-20T00:00:00",Sales:1173550.0)
					"51"(SaleDate:"2014-02-21T00:00:00",Sales:1252100.0)
					"52"(SaleDate:"2014-02-22T00:00:00",Sales:1244100.0)
					"53"(SaleDate:"2014-02-23T00:00:00",Sales:1244550.0)
					"54"(SaleDate:"2014-02-24T00:00:00",Sales:1277450.0)
					"55"(SaleDate:"2014-02-25T00:00:00",Sales:1253200.0)
					"56"(SaleDate:"2014-02-26T00:00:00",Sales:1155000.0)
					"57"(SaleDate:"2014-02-27T00:00:00",Sales:1160500.0)
					"58"(SaleDate:"2014-02-28T00:00:00",Sales:1187350.0)
					"59"(SaleDate:"2014-03-01T00:00:00",Sales:1043050.0)
					"60"(SaleDate:"2014-03-02T00:00:00",Sales:1031500.0)
					"61"(SaleDate:"2014-03-03T00:00:00",Sales:956350.0)
					"62"(SaleDate:"2014-03-04T00:00:00",Sales:1076650.0)
					"63"(SaleDate:"2014-03-05T00:00:00",Sales:1206100.0)
					"64"(SaleDate:"2014-03-06T00:00:00",Sales:999150.0)
					"65"(SaleDate:"2014-03-07T00:00:00",Sales:1099250.0)
					"66"(SaleDate:"2014-03-08T00:00:00",Sales:1154800.0)
					"67"(SaleDate:"2014-03-09T00:00:00",Sales:1047050.0)
					"68"(SaleDate:"2014-03-10T00:00:00",Sales:1295400.0)
					"69"(SaleDate:"2014-03-11T00:00:00",Sales:1267300.0)
					"70"(SaleDate:"2014-03-12T00:00:00",Sales:1247650.0)
					"71"(SaleDate:"2014-03-13T00:00:00",Sales:1233000.0)
					"72"(SaleDate:"2014-03-14T00:00:00",Sales:1157050.0)
					"73"(SaleDate:"2014-03-15T00:00:00",Sales:1293000.0)
					"74"(SaleDate:"2014-03-16T00:00:00",Sales:1211500.0)
					"75"(SaleDate:"2014-03-17T00:00:00",Sales:1191450.0)
					"76"(SaleDate:"2014-03-18T00:00:00",Sales:1319600.0)
					"77"(SaleDate:"2014-03-19T00:00:00",Sales:1318900.0)
					"78"(SaleDate:"2014-03-20T00:00:00",Sales:1279650.0)
					"79"(SaleDate:"2014-03-21T00:00:00",Sales:1266600.0)
					"80"(SaleDate:"2014-03-22T00:00:00",Sales:1295500.0)
					"81"(SaleDate:"2014-03-23T00:00:00",Sales:1145550.0)
					"82"(SaleDate:"2014-03-24T00:00:00",Sales:1311200.0)
					"83"(SaleDate:"2014-03-25T00:00:00",Sales:1317950.0)
					"84"(SaleDate:"2014-03-26T00:00:00",Sales:1232450.0)
					"85"(SaleDate:"2014-03-27T00:00:00",Sales:1138950.0)
					"86"(SaleDate:"2014-03-28T00:00:00",Sales:1274600.0)
					"87"(SaleDate:"2014-03-29T00:00:00",Sales:1284500.0)
					"88"(SaleDate:"2014-03-30T00:00:00",Sales:1197450.0)
					"89"(SaleDate:"2014-03-31T00:00:00",Sales:1209750.0)
					"90"(SaleDate:"2014-04-01T00:00:00",Sales:975550.0)
					"91"(SaleDate:"2014-04-02T00:00:00",Sales:963550.0)
					"92"(SaleDate:"2014-04-03T00:00:00",Sales:1094750.0)
					"93"(SaleDate:"2014-04-04T00:00:00",Sales:998150.0)
					"94"(SaleDate:"2014-04-05T00:00:00",Sales:1168500.0)
					"95"(SaleDate:"2014-04-06T00:00:00",Sales:1094350.0)
					"96"(SaleDate:"2014-04-07T00:00:00",Sales:1135200.0)
					"97"(SaleDate:"2014-04-08T00:00:00",Sales:997550.0)
					"98"(SaleDate:"2014-04-09T00:00:00",Sales:1078800.0)
					"99"(SaleDate:"2014-04-10T00:00:00",Sales:1225100.0)
					"100"(SaleDate:"2014-04-11T00:00:00",Sales:1318550.0)
					"101"(SaleDate:"2014-04-12T00:00:00",Sales:1319400.0)
					"102"(SaleDate:"2014-04-13T00:00:00",Sales:1193700.0)
					"103"(SaleDate:"2014-04-14T00:00:00",Sales:1318750.0)
					"104"(SaleDate:"2014-04-15T00:00:00",Sales:1236650.0)
					"105"(SaleDate:"2014-04-16T00:00:00",Sales:1332100.0)
					"106"(SaleDate:"2014-04-17T00:00:00",Sales:1264500.0)
					"107"(SaleDate:"2014-04-18T00:00:00",Sales:1218250.0)
					"108"(SaleDate:"2014-04-19T00:00:00",Sales:1256600.0)
					"109"(SaleDate:"2014-04-20T00:00:00",Sales:1231350.0)
					"110"(SaleDate:"2014-04-21T00:00:00",Sales:1244200.0)
					"111"(SaleDate:"2014-04-22T00:00:00",Sales:1125400.0)
					"112"(SaleDate:"2014-04-23T00:00:00",Sales:1162350.0)
					"113"(SaleDate:"2014-04-24T00:00:00",Sales:1168700.0)
					"114"(SaleDate:"2014-04-25T00:00:00",Sales:1198500.0)
					"115"(SaleDate:"2014-04-26T00:00:00",Sales:1204450.0)
					"116"(SaleDate:"2014-04-27T00:00:00",Sales:1351850.0)
				}
			}
		}else if (params?.day) {
			render(contentType:"text/json") {
				array{
					"0"(SaleDate:	"2014-04-01T08:00:00", Sales:975550)
					"1"(SaleDate:	"2014-04-01T09:00:00", Sales:963550)
					"2"(SaleDate:	"2014-04-01T10:00:00", Sales:1094750)
					"3"(SaleDate:	"2014-04-01T11:00:00", Sales:998150)
					"4"(SaleDate:	"2014-04-01T12:00:00", Sales:1168500)
					"5"(SaleDate:	"2014-04-01T13:00:00", Sales:1094350)
				}
			}
		}else if (params?.month){
			render(contentType:"text/json") {
				array{
					"0"(SaleDate:	"2014-04-01T00:00:00", Sales:975550)
					"1"(SaleDate:	"2014-04-02T00:00:00", Sales:963550)
					"2"(SaleDate:	"2014-04-03T00:00:00", Sales:1094750)
					"3"(SaleDate:	"2014-04-04T00:00:00", Sales:998150)
					"4"(SaleDate:	"2014-04-05T00:00:00", Sales:1168500)
					"5"(SaleDate:	"2014-04-06T00:00:00", Sales:1094350)
				}
			}
		} else{
			render(contentType:"text/json") {
				DailyPerformance(TodaySales:0, YesterdaySales:1125400, LastWeekSales: 8820550)
				MonthlyPerformance(ThisMonthSales:	25790950, LastMonthSales:37102900, YTDSales:133555650)
				AnnualPerformance(YTDSales:	133555650, ForecastSales:	435559422.9165164, LastYearSales : 434180400)
				SalesBySector = array{
					"0"(Criteria:"Telecom", Sales:198480400, Units:101564)
					"1"(Criteria:"Insurance", Sales:132846950, Units:67906)
					"2"(Criteria:"Manufacturing", Sales:201035950, Units:102836)
					"3"(Criteria:"Energy", Sales:333208750, Units:170044)
					"4"(Criteria:"Banking", Sales:65637600, Units:33503)
					"5"(Criteria:"Health", Sales:66952200, Units:34212)
				}
			}
		}
	}

	def product (){
		if (params?.startDate && params.endDate) {
			render(contentType:"text/json") {
				array{
					"0"(Criteria:"实木地板",Sales:254874,Units:866)
					"1"(Criteria:"强化地板",Sales:448935,Units:3365)
				}
			}
		}else if (params?.month){
			render(contentType:"text/json") {
				array{
					"0"(Criteria:"实木地板",Sales:254874,Units:866)
					"1"(Criteria:"强化地板",Sales:448935,Units:3365)
				}
			}
		}else if(params?.day){
			render(contentType:"text/json") {
				array{
					"0"(Criteria:"实木地板",Sales:254874,Units:866)
					"1"(Criteria:"强化地板",Sales:448935,Units:3365)
				}
			}
		} else{
			render(contentType:"text/json") {
				[TodaySales:100000
				,YesterdaySales:120000
				,LastWeekSales:1234567
				,ThisMonthUnits:0
				,LastMonthUnits:149 + 567
				,YtdUnits:305 + 1114]
			}
		}
	}

	def sector (){
		if (params?.startDate && params.endDate) {
			render(contentType:"text/json") {
				array{

grails-app/controllers/com/cyberoller/xbi/chartjs/DashboardController.groovy
package com.cyberoller.xbi.chartjs

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

import grails.converters.JSON

@Transactional(readOnly = true)
class DashboardController {

	def dashboardService
	def currentUserId

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

	def beforeInterceptor = {
		currentUserId = dashboardService.currentUserId()
	}

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond view : "/chartjs/dashboard/index", Dashboard.list(params), model:[ dashboardInstanceCount: Dashboard.count()]
    }

    def show(Dashboard dashboardInstance) {
        respond view : "/chartjs/dashboard/show", dashboardInstance
    }

    def create() {
        respond new Dashboard(params), view : "/chartjs/dashboard/create", model : [currentUserId : currentUserId]
    }

    @Transactional
    def save(Dashboard dashboardInstance) {
        if (dashboardInstance == null) {
            notFound()
            return
        }

        if (dashboardInstance.hasErrors()) {
            respond dashboardInstance.errors, view:'/chartjs/dashboard/create', model : [currentUserId : currentUserId]
            return
        }

        dashboardInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'dashboardInstance.label', default: 'Dashboard'), dashboardInstance.id])
                redirect dashboardInstance
            }
            '*' { respond dashboardInstance, [status: CREATED] }
        }
    }

    def edit(Dashboard dashboardInstance) {
        respond dashboardInstance, view : '/chartjs/dashboard/edit', model : [currentUserId : currentUserId]
    }

    @Transactional
    def update(Dashboard dashboardInstance) {
        if (dashboardInstance == null) {
            notFound()
            return
        }

        if (dashboardInstance.hasErrors()) {
            respond dashboardInstance.errors, view:'/chartjs/dashboard/edit', model : [currentUserId : currentUserId]
            return
        }

        dashboardInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Dashboard.label', default: 'Dashboard'), dashboardInstance.id])
                redirect dashboardInstance
            }
            '*'{ respond dashboardInstance, [status: OK] }
        }
    }

    protected void notFound() {
		log.info "*******************************not found"
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'dashboardInstance.label', default: 'Dashboard'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }

	/*运行*/
	def run(Dashboard dashboardInstance) {
		try {
			respond view : "/chartjs/dashboard/run", dashboardInstance
		} catch(Exception e){
			flash.error = "Dashboard ${id} encountered an error: ${e.message}"
			redirect(action:"${params.action}")
		}
        return
    }

	/*获取模板*/
	def template (Long id) {
		def content = ""
		try{
			//獲取目錄
			String applicationPath = request.getSession().getServletContext().getRealPath("")
			def dashboardHome = "${applicationPath}/xbi/dashboard"
			content = dashboardService.template(id, dashboardHome)
		}catch(e){
			response.status = 500
			content = e.getMessage()
		}
	    render content
		return
	}
	/*获取数据*/
	def data (Long id, String sql) {
		def data = ""
		try{
			data = dashboardService.data(id, sql)
		}catch(e){
			response.status = 500
			data = e.getMessage()
		}
	    render data
		return
	}
	
	/*上传*/
	@Transactional(readOnly=false)
    def upload(Long id) {
		try{
			//獲取文件
			def source = request.getFile("xfile")
			//判斷文件大小
			if(source.isEmpty()){
				throw new RuntimeException("空文件！")
			}
			//獲取儀表盤實例
			def dashboardInstance = Dashboard.withCriteria(uniqueResult:true){
				eq("id", id)
			}
			if(!dashboardInstance){
				throw new RuntimeException("获取仪表盘实例${id}错误")
			}
			//獲取目錄
			String applicationPath = request.getSession().getServletContext().getRealPath("")
			def dashboardHome = "${applicationPath}/xbi/dashboard"
			
			String xfile_name = "${dashboardInstance.name}.html"//获得文件原始的名称
			
			def xfile = new File("${dashboardHome}/${xfile_name}")
			if(xfile.exists()){
				xfile.delete()//删除旧文件
			}
			if(!xfile.exists()){
				xfile.mkdirs()//目录不存在则创建
			}
			source.transferTo( xfile )

		}catch(e){
			flash.message = e.getMessage()
		}
		redirect action:"show", id: id, method:"GET"
    }
}

grails-app/views/chartjs/dashboard/_edit.gsp
<%@ page import="com.cyberoller.xbi.chartjs.Dashboard" %>

<div class="fieldcontain ${hasErrors(bean: dashboardInstance, field: 'name', 'error')} ">
	<label for="name">
		<g:message code="dashboard.name.label" default="Name" />
	</label>
	<g:textField name="name" maxlength="20" value="${dashboardInstance?.name}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: dashboardInstance, field: 'author', 'error')} ">
	<label for="author">
		<g:message code="dashboard.author.label" default="Author" />
	</label>
	<g:textField name="author" maxlength="20" value="${dashboardInstance?.author}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: dashboardInstance, field: 'title', 'error')} ">
	<label for="title">
		<g:message code="dashboard.title.label" default="Title" />
	</label>
	<g:textField name="title" maxlength="200" value="${dashboardInstance?.title}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: dashboardInstance, field: 'datasource', 'error')} required">
	<label for="datasource">
		<g:message code="dashboard.datasource.label" default="Datasource" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="datasource" name="datasource.id" from="${com.cyberoller.xbi.chartjs.DataSource.list()}" optionKey="id" required="" value="${dashboardInstance?.datasource?.id}" class="many-to-one"/>
</div>

<div class="fieldcontain ${hasErrors(bean: dashboardInstance, field: 'description', 'error')} ">
	<label for="description">
		<g:message code="dashboard.description.label" default="Description" />
	</label>
	<g:textField name="description" maxlength="200" value="${dashboardInstance?.description}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: dashboardInstance, field: 'atMenu', 'error')} ">
	<label for="atMenu">
		<g:message code="dashboard.atMenu.label" default="At Menu?" />
	</label>
	<g:checkBox name="atMenu" value="${dashboardInstance?.atMenu}" />
</div>

<div class="fieldcontain ${hasErrors(bean: dashboardInstance, field: 'menuOrder', 'error')} ">
	<label for="menuOrder">
		<g:message code="dashboard.menuOrder.label" default="Menu Order" />
	</label>
	<g:textField name="menuOrder" maxlength="2" value="${dashboardInstance?.menuOrder}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: dashboardInstance, field: 'homePage', 'error')} ">
	<label for="homePage">
		<g:message code="dashboard.homePage.label" default="Home Page?" />
	</label>
	<g:checkBox name="homePage" value="${dashboardInstance?.homePage}" />
</div>

<div class="fieldcontain ${hasErrors(bean: dashboardInstance, field: 'isActive', 'error')} ">
	<label for="isActive">
		<g:message code="dashboard.isActive.label" default="Is Active" />
	</label>
	<g:checkBox name="isActive" value="${dashboardInstance?.isActive}" />
</div>

grails-app/views/chartjs/dashboard/_list.gsp
<%@ page import="com.cyberoller.xbi.chartjs.Dashboard" %>
<table>
	<thead>
		<tr>
			<g:sortableColumn property="name" title="${message(code: 'dashboard.name.label', default: 'Name')}" />
			<g:sortableColumn property="author" title="${message(code: 'dashboard.author.label', default: 'Author')}" />
			<g:sortableColumn property="title" title="${message(code: 'dashboard.title.label', default: 'Title')}" />
			<g:sortableColumn property="description" title="${message(code: 'dashboard.description.label', default: 'Description')}" />
			<g:sortableColumn property="isActive" title="${message(code: 'dashboard.isActive.label', default: 'Is Active')}" />
			<g:sortableColumn property="dateCreated" title="${message(code: 'dashboard.dateCreated.label', default: 'Date Created')}" />
			<g:sortableColumn property="lastUpdated" title="${message(code: 'dashboard.lastUpdated.label', default: 'Last Updated')}" />
			<th><g:message code="dashboard.button.run.label" default="RUN" /></th>
		</tr>
	</thead>
	<tbody>
		<g:each in="${dashboardInstanceList}" status="i" var="dashboardInstance">
		<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
			<td>
				<g:link action="show" id="${dashboardInstance.id}">${fieldValue(bean: dashboardInstance, field: "name")}</g:link>
			</td>
			<td>${fieldValue(bean: dashboardInstance, field: "author")}</td>
			<td>${fieldValue(bean: dashboardInstance, field: "title")}</td>
			<td>${fieldValue(bean: dashboardInstance, field: "description")}</td>
			<td><g:formatBoolean boolean="${dashboardInstance.isActive}" /></td>
			<td><g:formatDate date="${dashboardInstance.dateCreated}" /></td>
			<td><g:formatDate date="${dashboardInstance.lastUpdated}" /></td>
			<td>
				<g:link action="run" id="${dashboardInstance?.id}" params="[action:'list']">
					<g:message code="dashboard.button.run.label" default="RUN" />
				</g:link>
			</td>
		</tr>
		</g:each>
	</tbody>
</table>
<div class="pagination">
	<g:paginate total="${dashboardInstanceCount ?: 0}" />
</div>

grails-app/views/chartjs/dashboard/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'dashboard.label', default: 'Dashboard')}" />
		<title>
			<g:message code="default.create.label" args="[entityName]" />
			~
			<g:message code="global.app.name" />
		</title>
	</head>
	<body>
		<a href="#create-dashboard" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>

		<div id="create-dashboard" class="content scaffold-create" role="main">

			<h1><g:message code="default.create.label" args="[entityName]" /></h1>

			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>

			<g:hasErrors bean="${dashboardInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${dashboardInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>

			<g:form url="[resource:dashboardInstance, action:'save']" >
				<fieldset class="form">
					
					<g:hiddenField name="owner.id" value="${currentUserId}" />
					<g:hiddenField name="createdBy.id" value="${currentUserId}" />
					<g:hiddenField name="lastModifiedBy.id" value="${currentUserId}" />

					<g:render template="/chartjs/dashboard/edit" />
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>