grails-app/domain/com/cyberoller/xbi/Xfolder.groovy
package com.cyberoller.xbi

import com.cyberoller.xbi.shiro.User

/*文件夹*/
class Xfolder {

	static hasMany = [xfiles : Xfile]

	//父文件夹
	Xfolder xfolder
	//序号
	String serialNumber
	//名称
	String name
	//图标
	String icon
	//备注
	String description
	//所有人
	User owner
	//创建人
	User createdBy
	//修改人
	User lastModifiedBy
	//创建日期
	Date dateCreated
	//修改日期
	Date lastUpdated

    static constraints = {
		xfolder(nullable:true)
		serialNumber(nullable:false, blank:false, maxSize:4, unique:'xfolder')
		name(nullable:false, blank:false, maxSize : 50)
		icon(nullable:false, blank:false, maxSize : 100)
		description(nullable:true, blank:true, maxSize : 200)
		owner(nullable:false)
		createdBy(nullable:false)
		lastModifiedBy(nullable:false)
    }

    String toString(){
    	return "${name}"
    }
    
    static mapping = {
        table "xbi_folder"
    }
}

grails-app/controllers/com/cyberoller/xbi/XfolderController.groovy
package com.cyberoller.xbi

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class XfolderController {

	def xfolderService

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

	def currentUserId

	def beforeInterceptor = {
		//删除参数
		params.remove("shiroPostRedirect")
		currentUserId = xfolderService.currentUserId()
	}


	def fullpath(Long id){
		def fullpath = ""
		try{
			fullpath = xfolderService.fullpath(params.int('id').toLong())
		}catch(e){
			fullpath = "/e/"
		}
		render "${fullpath}"
		return
	}

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond  view : "/xfolder/index", xfolderService.list(params), model:[xfolderInstanceCount: xfolderService.count(params)]
    }

    def show(Xfolder xfolderInstance) {
		log.info "action is : xfolder.show"
        respond view : "/xfolder/show", xfolderInstance
    }

    def create() {
		try{
			def parentId = params.int('xfolder').toLong()
			def fullpath = xfolderService.fullpath(parentId)
			respond new Xfolder(params), view : "/xfolder/create", model : [fullpath : fullpath, currentUserId : currentUserId]
		}catch(e){
			flash.message = e.getMessage()
			redirect action:"index", method:"GET"
		}
    }

    @Transactional
    def save(Xfolder xfolderInstance) {
        if (xfolderInstance == null) {
            notFound()
            return
        }

        if (xfolderInstance.hasErrors()) {
			def parentId = params.int('xfolder.id').toLong()
			def fullpath = xfolderService.fullpath(parentId)
			respond xfolderInstance.errors, view:'/xfolder/create', model : [fullpath : fullpath, currentUserId : currentUserId]
            return
        }

        xfolderInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'xfolderInstance.label', default: 'Xfolder'), xfolderInstance.id])
                redirect xfolderInstance
            }
            '*' { respond xfolderInstance, [status: CREATED] }
        }
    }

    def edit(Xfolder xfolderInstance) {
		try{
			def folderId = xfolderInstance?.id?:-1L
			def fullpath = ""
			if(folderId != -1L){
				fullpath = xfolderService.fullpath(folderId)
			}else{
				fullpath = "/"
			}
			respond xfolderInstance, view : "/xfolder/edit", model : [fullpath : fullpath, currentUserId : currentUserId]
		}catch(e){
			flash.message = e.getMessage()
			redirect action:"index", method:"GET"
		}
        
    }

    @Transactional
    def update(Xfolder xfolderInstance) {
        if (xfolderInstance == null) {
            notFound()
            return
        }

        if (xfolderInstance.hasErrors()) {
			def folderId = xfolderInstance?.id?:-1L
			def fullpath = ""
			if(folderId != -1L){
				fullpath = xfolderService.fullpath(folderId)
			}else{
				fullpath = "/"
			}
			respond xfolderInstance.errors, view:'/Xfolder/edit', model : [fullpath : fullpath, currentUserId : currentUserId]
            return
        }

        xfolderInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Xfolder.label', default: 'Xfolder'), xfolderInstance.id])
                redirect xfolderInstance
            }
            '*'{ respond xfolderInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Xfolder xfolderInstance) {

        if (xfolderInstance == null) {
            notFound()
            return
        }

        xfolderInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Xfolder.label', default: 'Xfolder'), xfolderInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'xfolderInstance.label', default: 'Xfolder'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/xfolder/_edit.gsp
<%@ page import="com.cyberoller.xbi.Xfolder" %>

<div class="fieldcontain ${hasErrors(bean: xfolderInstance, field: 'xfolder', 'error')} ">
	<label for="xfolder">
		<g:message code="xfolder.xfolder.label" default="Xfolder" />
	</label>
	<g:if test="${fullpath}">
		${fullpath}
	</g:if>
	<g:else>
		${xfolderInstance?.xfolder?.name}
	</g:else>
	<g:hiddenField name="xfolder.id" value="${xfolderInstance?.xfolder?.id}" />
</div>

<div class="fieldcontain ${hasErrors(bean: xfolderInstance, field: 'serialNumber', 'error')} required">
	<label for="serialNumber">
		<g:message code="xfolder.serialNumber.label" default="Serial Number" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="serialNumber" maxlength="4" required="" value="${xfolderInstance?.serialNumber}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: xfolderInstance, field: 'name', 'error')} required">
	<label for="name">
		<g:message code="xfolder.name.label" default="Name" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="name" maxlength="50" required="" value="${xfolderInstance?.name}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: xfolderInstance, field: 'description', 'error')} ">
	<label for="description">
		<g:message code="xfolder.description.label" default="Description" />
		
	</label>
	<g:textField name="description" maxlength="200" value="${xfolderInstance?.description}"/>
</div>

grails-app/views/xfolder/_index.gsp
<%@ page import="com.cyberoller.xbi.Xfolder" %>
<table>
<thead>
		<tr>
			<g:sortableColumn property="serialNumber" title="${message(code: 'xfolder.serialNumber.label', default: 'Serial Number')}" />
			<g:sortableColumn property="name" title="${message(code: 'xfolder.name.label', default: 'Name')}" />
			<g:sortableColumn property="description" title="${message(code: 'xfolder.description.label', default: 'Description')}" />
			<th><g:message code="xfolder.owner.label" default="Owner" /></th>
			<th><g:message code="xfolder.createdBy.label" default="Created By" /></th>
			<th><g:message code="xfolder.lastModifiedBy.label" default="Last Modified By" /></th>
		</tr>
	</thead>
	<tbody>
	<g:each in="${xfolderInstanceList}" status="i" var="xfolderInstance">
		<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
			<td>
				<g:link action="show" id="${xfolderInstance.id}">
					${fieldValue(bean: xfolderInstance, field: "serialNumber")}
				</g:link>
				&nbsp;
				<g:link controller="xfolder" action="create" params="[xfolder:xfolderInstance.id]">
					(+)
				</g:link>
			</td>
			<td>
				<g:if test="${xfolderInstance.xfolder}">
						${include(action:'fullpath', id : xfolderInstance.id)}
				</g:if>
				<g:else>
						/${fieldValue(bean: xfolderInstance, field: "name")}
				</g:else>
			</td>
			<td>${fieldValue(bean: xfolderInstance, field: "description")}</td>
			<td>${fieldValue(bean: xfolderInstance, field: "owner")}</td>
			<td>
				${fieldValue(bean: xfolderInstance, field: "createdBy")}, ${formatDate(date:xfolderInstance?.dateCreated)}
			</td>
			<td>
				${fieldValue(bean: xfolderInstance, field: "lastModifiedBy")}, ${formatDate(date:xfolderInstance?.lastUpdated)}
			</td>
		</tr>
	</g:each>
	</tbody>
</table>
<div class="pagination">
	<g:paginate total="${XFolderInstanceCount ?: 0}" />
</div>

grails-app/views/xfolder/_show.gsp
<%@ page import="com.cyberoller.xbi.Xfolder" %>
<ol class="property-list xfolder">

	<g:if test="${xfolderInstance?.xfolder}">
	<li class="fieldcontain">
		<span id="xfolder-label" class="property-label"><g:message code="xfolder.xfolder.label" default="Xfolder" /></span>
		<span class="property-value" aria-labelledby="xfolder-label">
			<g:link controller="xfolder" action="show" id="${xfolderInstance?.xfolder?.id}">
				${include(action:'fullpath', id : xfolderInstance.id)}
			</g:link>
		</span>
	</li>
	</g:if>

	<g:if test="${xfolderInstance?.serialNumber}">
	<li class="fieldcontain">
		<span id="serialNumber-label" class="property-label"><g:message code="xfolder.serialNumber.label" default="Serial Number" /></span>
		<span class="property-value" aria-labelledby="serialNumber-label"><g:fieldValue bean="${xfolderInstance}" field="serialNumber"/></span>
	</li>
	</g:if>

	<g:if test="${xfolderInstance?.name}">
	<li class="fieldcontain">
		<span id="name-label" class="property-label"><g:message code="xfolder.name.label" default="Name" /></span>
		<span class="property-value" aria-labelledby="name-label"><g:fieldValue bean="${xfolderInstance}" field="name"/></span>
	</li>
	</g:if>

	<g:if test="${xfolderInstance?.description}">
	<li class="fieldcontain">
		<span id="description-label" class="property-label"><g:message code="xfolder.description.label" default="Description" /></span>
		<span class="property-value" aria-labelledby="description-label"><g:fieldValue bean="${xfolderInstance}" field="description"/></span>
	</li>
	</g:if>

	<g:if test="${xfolderInstance?.owner}">
	<li class="fieldcontain">
		<span id="owner-label" class="property-label"><g:message code="xfolder.owner.label" default="Owner" /></span>
		<span class="property-value" aria-labelledby="owner-label">
			<g:link controller="user" action="show" id="${xfolderInstance?.owner?.id}">${xfolderInstance?.owner?.encodeAsHTML()}</g:link>
		</span>
	</li>
	</g:if>

	<g:if test="${xfolderInstance?.createdBy}">
	<li class="fieldcontain">
		<span id="createdBy-label" class="property-label"><g:message code="xfolder.createdBy.label" default="Created By" /></span>
		<span class="property-value" aria-labelledby="createdBy-label">
			<g:link controller="user" action="show" id="${xfolderInstance?.createdBy?.id}">${xfolderInstance?.createdBy?.encodeAsHTML()}</g:link>
		</span>
	</li>
	</g:if>

	<g:if test="${xfolderInstance?.lastModifiedBy}">
	<li class="fieldcontain">
		<span id="lastModifiedBy-label" class="property-label"><g:message code="xfolder.lastModifiedBy.label" default="Last Modified By" /></span>
		<span class="property-value" aria-labelledby="lastModifiedBy-label">
			<g:link controller="user" action="show" id="${xfolderInstance?.lastModifiedBy?.id}">${xfolderInstance?.lastModifiedBy?.encodeAsHTML()}</g:link>
		</span>
	</li>
	</g:if>

	<g:if test="${xfolderInstance?.dateCreated}">
	<li class="fieldcontain">
		<span id="dateCreated-label" class="property-label"><g:message code="xfolder.dateCreated.label" default="Date Created" /></span>
		<span class="property-value" aria-labelledby="dateCreated-label"><g:formatDate date="${xfolderInstance?.dateCreated}" /></span>
	</li>
	</g:if>

	<g:if test="${xfolderInstance?.lastUpdated}">
	<li class="fieldcontain">
		<span id="lastUpdated-label" class="property-label"><g:message code="xfolder.lastUpdated.label" default="Last Updated" /></span>
		<span class="property-value" aria-labelledby="lastUpdated-label"><g:formatDate date="${xfolderInstance?.lastUpdated}" /></span>
	</li>
	</g:if>


</ol>

<table>
	<caption>
		<g:message code="xfolder.xfiles.label" default="Xfiles" />
		&nbsp;
		<g:link controller="xfile" action="create" params="[xfolder:xfolderInstance.id]">(+)</g:link>
	</caption>
	<thead>
		<tr>
			<th><g:message code="xfile.serialNumber.label" default="Serial Number" /></th>
			<th><g:message code="xfile.xtype.label" default="Type" /></th>
			<th>
				<g:message code="xfile.report.label" default="Report" />
				/
				<g:message code="xfile.dashboard.label" default="Dashboard" />
			</th>
			<th><g:message code="xfile.owner.label" default="Owner" /></th>
			<th><g:message code="xfile.createdBy.label" default="Created By" /></th>
			<th><g:message code="xfile.lastModifiedBy.label" default="Last Modified By" /></th>
		</tr>
	</thead>
	<tbody>
	<g:each in="${xfolderInstance.xfiles?.sort{return it.serialNumber}}" status="i" var="xfileInstance">
		<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
			<td>
				<g:link controller="xfile" action="show" id="${xfileInstance.id}">
					${fieldValue(bean: xfileInstance, field: "serialNumber")}
				</g:link>
			</td>
			<td>${fieldValue(bean: xfileInstance, field: "xtype")}</td>
			<td>
				<g:if test="${xfileInstance?.xtype == 'Report'}">
					${fieldValue(bean: xfileInstance, field: "report")}
				</g:if>
				<g:if test="${xfileInstance?.xtype == 'Dashboard'}">
					${fieldValue(bean: xfileInstance, field: "dashboard")}
				</g:if>
			</td>
			<td>${fieldValue(bean: xfileInstance, field: "owner")}</td>
			<td>
				${fieldValue(bean: xfileInstance, field: "createdBy")}
				,
				${formatDate(date:xfileInstance?.dateCreated)}
			</td>
			<td>
				${fieldValue(bean: xfileInstance, field: "lastModifiedBy")}
				,
				${formatDate(date:xfileInstance?.lastUpdated)}	
			</td>
		</tr>
	</g:each>
	</tbody>
</table>

grails-app/views/xfolder/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">

		<g:set var="entityName" value="${message(code: 'XFolder.label', default: 'XFolder')}" />

		<title>
			<g:message code="default.create.label" args="[entityName]" />
			~
			<g:message code="global.app.name" />
		</title>

	</head>
	<body>
		<a href="#create-XFolder" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		
		<div id="create-XFolder" class="content scaffold-create" role="main">

			<h1><g:message code="default.create.label" args="[entityName]" /></h1>

			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>

			<g:hasErrors bean="${XFolderInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${XFolderInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>

			<g:form url="[resource:XFolderInstance, action:'save']" >

				<fieldset class="form">
					<g:hiddenField name="owner.id" value="${currentUserId}" />
					<g:hiddenField name="createdBy.id" value="${currentUserId}" />
					<g:hiddenField name="lastModifiedBy.id" value="${currentUserId}" />
					<g:render template="/xfolder/edit" />
				</fieldset>

				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>

			</g:form>
		</div>
	</body>
</html>

grails-app/views/xfolder/edit.gsp
<%@ page import="com.cyberoller.xbi.Xfolder" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">

		<g:set var="entityName" value="${message(code: 'xfolder.label', default: 'Folder')}" />

		<title>
			<g:message code="default.edit.label" args="[entityName]" />
			~
			<g:message code="global.app.name" />
		</title>
	</head>
	<body>
		<a href="#edit-xfolder" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>

		<div id="edit-xfolder" class="content scaffold-edit" role="main">

			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>

			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>

			<g:hasErrors bean="${xfolderInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${xfolderInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>

			<g:form url="[resource:xfolderInstance, action:'update']" method="PUT" >

				<g:hiddenField name="version" value="${xfolderInstance?.version}" />

				<fieldset class="form">
					<g:hiddenField name="lastModifiedBy.id" value="${currentUserId}" />
					<g:render template="/xfolder/edit" />
				</fieldset>

				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>

			</g:form>
		</div>
	</body>
</html>

grails-app/views/xfolder/index.gsp
<%@ page import="com.cyberoller.xbi.Xfolder" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">

		<g:set var="entityName" value="${message(code: 'xfolder.label', default: 'Folder')}" />

		<title>
			<g:message code="default.list.label" args="[entityName]" />
			~
			<g:message code="global.app.name" />
		</title>

	</head>
	<body>
		<a href="#list-Xfolder" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>

		<div id="list-Xfolder" class="content scaffold-list" role="main">
			
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			
			<g:render template="/xfolder/index" />

		</div>
	</body>
</html>

grails-app/views/xfolder/show.gsp
<%@ page import="com.cyberoller.xbi.Xfolder" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'xfolder.label', default: 'Folder')}" />
		<title>
			<g:message code="default.show.label" args="[entityName]" />
			~
			<g:message code="global.app.name" />
		</title>
	</head>
	<body>
		<a href="#show-xfolder" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>

		<div id="show-xfolder" class="content scaffold-show" role="main">

			<h1><g:message code="default.show.label" args="[entityName]" /></h1>

			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>

			<g:render template="/xfolder/show" />			

			<g:form url="[resource:xfolderInstance, action:'delete']" method="DELETE">

				<fieldset class="buttons">

					<g:link class="edit" action="edit" resource="${xfolderInstance}">
						<g:message code="default.button.edit.label" default="Edit" />
					</g:link>

					<g:actionSubmit class="delete" action="delete" 
						value="${message(code: 'default.button.delete.label', default: 'Delete')}"
						onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>

			</g:form>
		</div>
	</body>
</html>